#!/bin/bash

if [ $1 = "1" ] ; then
	./23tree < "$2" > "output.txt"
elif [ $1 = "2" ] ; then
	./rbtree < "$2" > "output.txt"
elif [ $1 = "3" ] ; then
	./avl2 < "$2" > "output.txt"
else
	./skip < "$2" > "output.txt"
fi
